name: build
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build_natives:
    permissions:
      contents: write
    name: Build natives libraries
    strategy:
      matrix:
        # os: [ ubuntu-latest, windows-latest ]
        os: [ windows-latest ]
        target: [ native ]
        # include:
        #   - os: ubuntu-latest
        #     target: mac64-signed
        #   - os: ubuntu-latest
        #     target: mac-arm64-signed
    runs-on: ${{ matrix.os }}
    steps:
      - name: Make space
        if: runner.os == 'Linux'
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          java-package: jdk
          cache: 'maven'

      - name: Source versions from VERSION file
        run: cat VERSION >> $GITHUB_ENV

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - uses: ilammy/setup-nasm@v1
        if: runner.os == 'Windows'
      - name: Build OpenSSL
        if: runner.os == 'Windows'
        run: |
          Invoke-Webrequest -URI https://www.openssl.org/source/openssl-1.1.1w.tar.gz -OutFile openssl-1.1.1w.tar.gz
          tar zxf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          perl Configure VC-WIN64A --prefix=C:\openssl1.1.1
          nmake
          nmake install
          cp C:\openssl1.1.1\bin\libcrypto-1_1-x64.dll C:\openssl1.1.1\bin\libcrypto.dll
          cp C:\openssl1.1.1\bin\libssl-1_1-x64.dll C:\openssl1.1.1\bin\libssl.dll

      - name: Zip OpenSSL build
        shell: bash
        run: zip -r openssl1.1.1w.zip C:\openssl1.1.1
      - uses: actions/upload-artifact@v3
        with:
          name: OpenSSL build
          path: |
            ./openssl1.1.1w.zip

      - name: Build binaries and package
        env:
          OCI_EXE: docker
        run: make ${{ matrix.target }} package

      - name: Set platform classifier
        shell: bash
        run: |
          if [[ ${{ runner.os }} == "Linux" ]]
          then
            if [[ ${{ matrix.target }} == "native" ]]
            then
              classifier=linux-x86_64
            elif [[ ${{ matrix.target }} == "mac64-signed" ]]
            then
              classifier=darwin-x86_64
            elif [[ ${{ matrix.target }} == "mac-arm64-signed" ]]
            then
              classifier=darwin-aarch64
            fi
          elif [[ ${{ runner.os }} == "Windows" ]]
          then
            classifier=win-x86_64
          fi
          echo "CLASSIFIER=$classifier" >> $GITHUB_ENV

      - name: Deploy version
        env:
          GLUON_NEXUS_USERNAME: ${{ secrets.GLUON_NEXUS_USERNAME }}
          GLUON_NEXUS_PASSWORD: ${{ secrets.GLUON_NEXUS_PASSWORD }}
        if: startsWith(github.ref, 'refs/tags/')
        run: make deploy
